### ISSUE TITLE
CSI OSC send problems

### ISSUE THREAD

**Issue by iliasboufidis** [GeoffAWaddington/reaper_csurf_integrator#13]
For reasons unknown to me, CSI here does not broadcast OSC out. The setup is using the same ports that work in other software. pings and tests of the ports and the network work ok for reaper's native osc implementation (bidirectionally). the same port setup works for reaktor and Touch OSC editor (which i'm trying to use in order to make a CSI display), generally as far as i can tell and looking into this for a couple of days as thoroughly as i can, CSI just doesn't send anything out. It receives and relays to reaper, and addresses are ok. 
If it's my fault, please help. if it's a bug, please help.

**Comment by DenisDangerous** [comment]
CSI works in one direction, but Lemur receives broadcast. Set osc0 for input and osc1 for output.  For faders and knobs in lemur set target osc0. And you can control with feedback.

**Comment by iliasboufidis** [comment]
thank you, i 'll close this issue now.
