### ISSUE TITLE
TrackAutoMode no longer seems to work.

### ISSUE THREAD

**Issue by AironAudio** [GeoffAWaddington/reaper_csurf_integrator#6]
The following for the Presonus Faderport 16 no longer works, but it used to.

The zone piece lives in a Buttons zone that has no channel stuff. That's in a zone with TrackNavigator active.
Also posted in this thread: [https://forum.cockos.com/showpost.php?p=2420082&postcount=12588](url)
**MST**
Widget Read
                Press 90 4a 7f
  FB_FaderportRGB7Bit 90 4a 7f
WidgetEnd
and so on for the other buttons

**Zone**
  Read         TrackAutoMode 1  { 0 4 0  0 96 0 }
  Write        TrackAutoMode 3  { 4 0 0  127 0 0 }
  Trim         TrackAutoMode 0  { 1 3 3  127 127 127 }
  Touch        TrackAutoMode 2  { 2 3 0  112 112 00 }
  Latch        TrackAutoMode 4  { 4 0 4  96 0 96 }
  Off          TrackAutoMode 5  { 0 0 10 0 32 127 }

**Comment by GeoffAWaddington** [comment]
You now need a SelectedTrackNavigator for TrackAutoMode
